version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
  krammatik:
    build: .
    container_name: krammatik-backend
    environment:
      - PUID=1000
      - PGID=1000
      - ENCRYPT_SECRET=${ENCRYPT_SECRET}
      - MONGO_CONNECTION_STRING=mongodb://127.0.0.1:27017
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mongo
    profiles:
      - deploy
